//! Firmware scaffolding — emit a starter node sketch for a registered board.
//!
//! Closes the **scout → registry → firmware → orchestrate** loop: once a board is
//! known to the registry (capabilities, VID/PID), the deployment planner can emit a
//! *starter* firmware sketch for it — capability-conditioned includes and init, plus
//! the OBC node protocol skeleton (announce on boot, read line-framed commands over
//! serial). It is a scaffold, not a finished firmware: it compiles in shape and
//! gives the operator a correct skeleton to fill in, instead of a blank file.
//!
//! Borrowed from a sibling project's firmware *templates* (Arduino/ESP32 config
//! generators) — the templates, not its codegen engine. Pure string assembly, no
//! deps.

use crate::peripherals::registry::BoardInfo;

/// Target source language for the generated sketch.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SketchLang {
    /// Arduino / ESP32 `.ino` C++ (the broad lowest-common-denominator target).
    Arduino,
}

/// Options for a scaffold.
#[derive(Debug, Clone)]
pub struct ScaffoldOptions {
    /// The node id the firmware announces itself as.
    pub node_id: String,
    /// Serial baud rate.
    pub baud: u32,
    pub lang: SketchLang,
}

impl Default for ScaffoldOptions {
    fn default() -> Self {
        Self { node_id: "obc-node".to_string(), baud: 115_200, lang: SketchLang::Arduino }
    }
}

/// A generated firmware sketch.
#[derive(Debug, Clone)]
pub struct FirmwareSketch {
    pub board: String,
    pub language: SketchLang,
    pub filename: String,
    pub source: String,
}

const SKETCH: &str = r#"// Auto-generated by Oh-Ben-Claw firmware scaffold — starter sketch; edit freely.
// Board: __BOARD__ (__IDS__)  vendor: __VENDOR__
// Capabilities: __CAPS_LIST__
// Node: __NODE_ID__
__INCLUDES__
const char* OBC_NODE_ID = "__NODE_ID__";
const char* OBC_BOARD    = "__BOARD__";

// Announce this node + its capabilities to the brain over serial on boot.
void announce() {
  Serial.print("{\"type\":\"announce\",\"node_id\":\"");
  Serial.print(OBC_NODE_ID);
  Serial.print("\",\"board\":\"");
  Serial.print(OBC_BOARD);
  Serial.println("\",\"capabilities\":[__CAPS_JSON__]}");
}

// Handle one line-framed command from the brain.
void handleCommand(const String& cmd) {
  // TODO: parse JSON and dispatch (ping, gpio_write, sensor_read, ...).
  if (cmd.indexOf("ping") >= 0) {
    Serial.println("{\"ok\":true,\"pong\":true}");
  }
}

void setup() {
  Serial.begin(__BAUD__);
  while (!Serial) {}
__SETUP_INIT__
  announce();
}

void loop() {
  if (Serial.available()) {
    String line = Serial.readStringUntil('\n');
    handleCommand(line);
  }
}
"#;

/// Generate a starter firmware sketch for `board`.
pub fn scaffold_firmware(board: &BoardInfo, opts: &ScaffoldOptions) -> FirmwareSketch {
    let has = |c: &str| board.capabilities.contains(&c);

    let includes = {
        let mut v: Vec<&str> = Vec::new();
        if has("wifi") {
            v.push("#include <WiFi.h>");
        }
        if has("ble") {
            v.push("#include <BLEDevice.h>");
        }
        if has("i2c") {
            v.push("#include <Wire.h>");
        }
        if has("spi") {
            v.push("#include <SPI.h>");
        }
        if has("camera_capture") {
            v.push("#include \"esp_camera.h\"");
        }
        if v.is_empty() {
            String::new()
        } else {
            format!("\n{}\n", v.join("\n"))
        }
    };

    let setup_init = {
        let mut v: Vec<&str> = Vec::new();
        if has("wifi") {
            v.push("  WiFi.mode(WIFI_STA);");
        }
        if has("i2c") {
            v.push("  Wire.begin();");
        }
        if has("spi") {
            v.push("  SPI.begin();");
        }
        v.join("\n")
    };

    // capability tokens, C-string-escaped, for the announce JSON array.
    let caps_json = board
        .capabilities
        .iter()
        .map(|c| format!("\\\"{c}\\\""))
        .collect::<Vec<_>>()
        .join(",");

    let source = SKETCH
        .replace("__BOARD__", board.name)
        .replace("__IDS__", &format!("{:04x}:{:04x}", board.vid, board.pid))
        .replace("__VENDOR__", board.vendor)
        .replace("__CAPS_LIST__", &board.capabilities.join(", "))
        .replace("__NODE_ID__", &opts.node_id)
        .replace("__INCLUDES__", &includes)
        .replace("__CAPS_JSON__", &caps_json)
        .replace("__BAUD__", &opts.baud.to_string())
        .replace("__SETUP_INIT__", &setup_init);

    FirmwareSketch {
        board: board.name.to_string(),
        language: opts.lang,
        filename: format!("{}_obc_node.ino", board.name),
        source,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::peripherals::registry::known_boards;

    fn board(name: &str) -> &'static BoardInfo {
        known_boards().iter().find(|b| b.name == name).expect("board in registry")
    }

    #[test]
    fn camera_board_gets_capability_conditioned_includes() {
        let opts = ScaffoldOptions { node_id: "cam-1".into(), ..Default::default() };
        let sk = scaffold_firmware(board("esp32-s3-cam"), &opts);
        assert!(sk.source.contains("#include <WiFi.h>"));
        assert!(sk.source.contains("#include <Wire.h>"));
        assert!(sk.source.contains("#include \"esp_camera.h\""));
        assert!(sk.source.contains("Wire.begin();"));
        assert!(sk.source.contains("Serial.begin(115200)"));
        assert!(sk.source.contains("void announce()") && sk.source.contains("void loop()"));
        assert!(sk.source.contains("cam-1"), "the node id is baked in");
        assert_eq!(sk.filename, "esp32-s3-cam_obc_node.ino");
        assert_eq!(sk.language, SketchLang::Arduino);
    }

    #[test]
    fn a_plain_board_pulls_in_no_radio_or_bus_headers() {
        // arduino-uno: gpio / analog only — no wifi / i2c / spi / camera.
        let sk = scaffold_firmware(board("arduino-uno"), &ScaffoldOptions::default());
        assert!(!sk.source.contains("WiFi.h"));
        assert!(!sk.source.contains("Wire.h"));
        assert!(!sk.source.contains("esp_camera.h"));
        // still a complete node skeleton
        assert!(sk.source.contains("void setup()") && sk.source.contains("announce();"));
    }

    #[test]
    fn the_announce_advertises_the_boards_capabilities() {
        let sk = scaffold_firmware(board("lilygo-t-beam"), &ScaffoldOptions::default());
        // t-beam has lora + gps + mesh — they appear in the announce array
        assert!(sk.source.contains(r#"\"lora\""#));
        assert!(sk.source.contains(r#"\"gps\""#));
        assert!(sk.source.contains(r#"\"capabilities\":["#));
    }

    #[test]
    fn baud_and_node_id_are_honored() {
        let opts = ScaffoldOptions { node_id: "rover-9".into(), baud: 921_600, lang: SketchLang::Arduino };
        let sk = scaffold_firmware(board("esp32-c3"), &opts);
        assert!(sk.source.contains("Serial.begin(921600)"));
        assert!(sk.source.contains("OBC_NODE_ID = \"rover-9\""));
    }
}
