//! OV2640 camera driver via the `espressif/esp32-camera` IDF component.
//!
//! Compiled only under `--features camera` (see CAMERA.md for the required
//! `idf_component.yml` + PSRAM sdkconfig). The bindings (`camera_config_t`,
//! `esp_camera_init`, `esp_camera_fb_get`, …) are generated by `esp-idf-sys`
//! from the component's headers, so they exist only when the component is present.
//!
//! **This pin map is not the Waveshare's, and no board is known to match it.**
//!
//! This header said "Pin map: Waveshare ESP32-S3 Touch LCD 2.1 (OV2640 via the
//! FPC connector)" from the day it was written. On 2026-08-21 Benji looked at
//! the board: its only FPC connector is the screen's. There is no camera
//! connector.
//!
//! It was alone in claiming otherwise, and three other places in this tree
//! already said so — `Cargo.toml` ("Not applicable to the Waveshare 2.1 board
//! (no camera connector)"), `docs/BENCH-PINOUT-CARDS.md` Card 3 ("Camera / I2S
//! mic: **not possible on this board** — stubs", corrected against the
//! Waveshare schematic on 2026-07-16), and
//! `docs/HARDWARE-TEST-WALKTHROUGH.md`. A file contradicting its own crate's
//! manifest two directories away went unnoticed because nothing compares them.
//!
//! Which board the map below *is* for is unknown. XCLK=15, SCCB=4/5 and
//! PCLK=13 match the Espressif ESP32-S3-EYE v2.2 (`docs/BENCH-BINDER.md`
//! Card 4), but that board's data bus is 11,9,8,10,12,18,17,16 and this one
//! uses 39,40,41,42,16,17,18,19. A partial match to one board is not a pin map
//! for it. Treat every number below as unattributed until someone checks it
//! against a datasheet for a board they are holding.
//!
//! **Do not build this with `board-waveshare-21`.** On that board the LCD
//! consumes GPIO 1–3, 5–14, 16–18, 21, 38–41 and 45–48, and GPIO 15 is the
//! hardwired I2C connector's SDA — so this map's D4–D7, VSYNC, HREF, D0–D2 and
//! XCLK all land on the display or the sensor bus. The combination is now
//! refused at compile time below.
//!
//! The sensor I2C bus is still disabled under `--features camera`. The original
//! reason ("the same pins as the sensor bus") stopped being true when the
//! default bus moved to GPIO5/6 on 2026-08-21, and it was never true of the
//! Waveshare's 15/7. The gate is kept because turning the bus on in a build
//! that has never run is a bench decision, not an edit.
//!
//! **Untested on metal by its author, and the highest-FFI-risk module in the tree.**
//! The struct field names (`pin_sccb_sda`/`pin_sccb_scl` in esp32-camera ≥2.0; the
//! older component spelled them `pin_sscb_*`) and the bindgen enum names are the
//! parts most likely to need a version tweak — verify against the compiler.

// Confirmed by looking at the board on 2026-08-21: the Waveshare
// ESP32-S3-Touch-LCD-2.1 has one FPC connector and it is the screen's. This
// map's pins are that board's LCD lines and its hardwired I2C SDA, so the
// combination cannot do anything but drive the display.
#[cfg(all(feature = "camera", feature = "board-waveshare-21"))]
compile_error!(
    "`camera` and `board-waveshare-21` are mutually exclusive: that board has no \
     camera connector, and this module's pins are its LCD lines. See camera.rs."
);

use anyhow::Context;
// esp32-camera bindings live in their own module (see Cargo.toml `bindings_module`).
use esp_idf_svc::sys::camera as sys;
// ESP_OK / error type come from the base bindings, not the camera module.
use esp_idf_svc::sys::ESP_OK;

/// Initialise the camera driver (global; call once at boot).
pub fn init() -> anyhow::Result<()> {
    // Zero-initialise the C config, then fill the fields this board needs.
    let mut cfg: sys::camera_config_t = unsafe { core::mem::zeroed() };

    cfg.pin_pwdn = -1;
    cfg.pin_reset = -1;
    cfg.pin_xclk = 15;
    // SCCB (camera-control I2C) pins live in anonymous unions in the binding — the
    // component keeps both the new `pin_sccb_*` and legacy `pin_sscb_*` spellings.
    // Writing a union field is safe in Rust.
    cfg.__bindgen_anon_1.pin_sccb_sda = 4;
    cfg.__bindgen_anon_2.pin_sccb_scl = 5;
    // 8-bit parallel data bus D0..D7.
    cfg.pin_d0 = 39;
    cfg.pin_d1 = 40;
    cfg.pin_d2 = 41;
    cfg.pin_d3 = 42;
    cfg.pin_d4 = 16;
    cfg.pin_d5 = 17;
    cfg.pin_d6 = 18;
    cfg.pin_d7 = 19;
    cfg.pin_vsync = 21;
    cfg.pin_href = 38;
    cfg.pin_pclk = 13;

    cfg.xclk_freq_hz = 20_000_000;
    cfg.ledc_timer = sys::ledc_timer_t_LEDC_TIMER_0;
    cfg.ledc_channel = sys::ledc_channel_t_LEDC_CHANNEL_0;

    cfg.pixel_format = sys::pixformat_t_PIXFORMAT_JPEG;
    cfg.frame_size = sys::framesize_t_FRAMESIZE_QVGA; // 320×240 — fits one PSRAM fb
    cfg.jpeg_quality = 12; // 0..63, lower = higher quality
    cfg.fb_count = 1;
    cfg.fb_location = sys::camera_fb_location_t_CAMERA_FB_IN_PSRAM;
    cfg.grab_mode = sys::camera_grab_mode_t_CAMERA_GRAB_WHEN_EMPTY;

    let err = unsafe { sys::esp_camera_init(&cfg) };
    if err != ESP_OK {
        anyhow::bail!("esp_camera_init failed (error {err})");
    }
    Ok(())
}

/// Capture one JPEG frame and return it base64-encoded.
pub fn capture_base64() -> anyhow::Result<String> {
    let fb = unsafe { sys::esp_camera_fb_get() };
    if fb.is_null() {
        anyhow::bail!("esp_camera_fb_get returned null (no frame)");
    }
    // Copy the frame out, then always return the buffer to the driver.
    let result = (|| {
        let len = unsafe { (*fb).len } as usize;
        let buf = unsafe { (*fb).buf };
        if buf.is_null() || len == 0 {
            anyhow::bail!("empty frame buffer");
        }
        let data = unsafe { core::slice::from_raw_parts(buf, len) };
        Ok(base64_encode(data))
    })();
    unsafe { sys::esp_camera_fb_return(fb) };
    result.context("camera capture")
}

/// Minimal standard base64 encoder (no external crate in the firmware deps).
fn base64_encode(input: &[u8]) -> String {
    const TABLE: &[u8; 64] =
        b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity((input.len() + 2) / 3 * 4);
    for chunk in input.chunks(3) {
        let b0 = chunk[0] as u32;
        let b1 = *chunk.get(1).unwrap_or(&0) as u32;
        let b2 = *chunk.get(2).unwrap_or(&0) as u32;
        let n = (b0 << 16) | (b1 << 8) | b2;
        out.push(TABLE[((n >> 18) & 0x3F) as usize] as char);
        out.push(TABLE[((n >> 12) & 0x3F) as usize] as char);
        out.push(if chunk.len() > 1 {
            TABLE[((n >> 6) & 0x3F) as usize] as char
        } else {
            '='
        });
        out.push(if chunk.len() > 2 {
            TABLE[(n & 0x3F) as usize] as char
        } else {
            '='
        });
    }
    out
}
