//! OV2640 camera driver via the `espressif/esp32-camera` IDF component.
//!
//! Compiled only under `--features camera` (see CAMERA.md for the required
//! `idf_component.yml` + PSRAM sdkconfig). The bindings (`camera_config_t`,
//! `esp_camera_init`, `esp_camera_fb_get`, …) are generated by `esp-idf-sys`
//! from the component's headers, so they exist only when the component is present.
//!
//! **This pin map is not the Waveshare's, and no board is known to match it.**
//!
//! This header said "Pin map: Waveshare ESP32-S3 Touch LCD 2.1 (OV2640 via the
//! FPC connector)" from the day it was written. On 2026-08-21 Benji looked at
//! the board: its only FPC connector is the screen's. There is no camera
//! connector.
//!
//! It was alone in claiming otherwise, and three other places in this tree
//! already said so — `Cargo.toml` ("Not applicable to the Waveshare 2.1 board
//! (no camera connector)"), `docs/BENCH-PINOUT-CARDS.md` Card 3 ("Camera / I2S
//! mic: **not possible on this board** — stubs", corrected against the
//! Waveshare schematic on 2026-07-16), and
//! `docs/HARDWARE-TEST-WALKTHROUGH.md`. A file contradicting its own crate's
//! manifest two directories away went unnoticed because nothing compares them.
//!
//! Which board the map below *is* for is unknown. XCLK=15, SCCB=4/5 and
//! PCLK=13 match the Espressif ESP32-S3-EYE v2.2 (`docs/BENCH-BINDER.md`
//! Card 4), but that board's data bus is 11,9,8,10,12,18,17,16 and this one
//! uses 39,40,41,42,16,17,18,19. A partial match to one board is not a pin map
//! for it. Treat every number below as unattributed until someone checks it
//! against a datasheet for a board they are holding.
//!
//! **Do not build this with `board-waveshare-21`.** On that board the LCD
//! consumes GPIO 1–3, 5–14, 16–18, 21, 38–41 and 45–48, and GPIO 15 is the
//! hardwired I2C connector's SDA — so this map's D4–D7, VSYNC, HREF, D0–D2 and
//! XCLK all land on the display or the sensor bus. The combination is now
//! refused at compile time below.
//!
//! The sensor I2C bus is still disabled under `--features camera`. The original
//! reason ("the same pins as the sensor bus") stopped being true when the
//! default bus moved to GPIO5/6 on 2026-08-21, and it was never true of the
//! Waveshare's 15/7. The gate is kept because turning the bus on in a build
//! that has never run is a bench decision, not an edit.
//!
//! **Untested on metal by its author, and the highest-FFI-risk module in the tree.**
//! The struct field names (`pin_sccb_sda`/`pin_sccb_scl` in esp32-camera ≥2.0; the
//! older component spelled them `pin_sscb_*`) and the bindgen enum names are the
//! parts most likely to need a version tweak — verify against the compiler.
//!
//! ---
//!
//! **2026-09-16: the pin map is now a per-board choice, and there is no default.**
//!
//! The map above was wrong twice because it was a single hard-coded set with no
//! board attached to it, and nothing forced anyone to say which board they meant.
//! A default is what let "the Waveshare's pins" survive for weeks on a board with
//! no camera connector. So `--features camera` alone no longer compiles: it needs
//! a board feature too, and the unattributed set is quarantined behind
//! `board-unverified-map` rather than deleted — the history above is worth more
//! than the twelve numbers, and deleting it would invite someone to re-derive the
//! same guess.

// Confirmed by looking at the board on 2026-08-21: the Waveshare
// ESP32-S3-Touch-LCD-2.1 has one FPC connector and it is the screen's. This
// map's pins are that board's LCD lines and its hardwired I2C SDA, so the
// combination cannot do anything but drive the display.
#[cfg(all(feature = "camera", feature = "board-waveshare-21"))]
compile_error!(
    "`camera` and `board-waveshare-21` are mutually exclusive: that board has no \
     camera connector, and this module's pins are its LCD lines. See camera.rs."
);

// A camera build must name its board. No default: see the 2026-09-16 note above.
#[cfg(all(
    feature = "camera",
    not(any(
        feature = "board-xiao-sense",
        feature = "board-lilygo-tcam-s3-v11",
        feature = "board-unverified-map"
    ))
))]
compile_error!(
    "`camera` needs a board feature so the pin map is attributable. Add \
     `board-xiao-sense` (Seeed XIAO ESP32S3 Sense, pins from the vendor wiki), \
     `board-lilygo-tcam-s3-v11` (LILYGO T-CameraPlus-S3 **V1.0/V1.1 only** -- V1.2 \
     moves VSYNC/PWDN/RESET and is a different board), or, only if you know what it \
     is for, `board-unverified-map` (the historical unattributed set — matches no \
     known board). See camera.rs."
);

// Pairwise, because each pin map is a different board and picking two means the
// compiler silently takes whichever `cfg` it sees first.
#[cfg(all(feature = "board-xiao-sense", feature = "board-unverified-map"))]
compile_error!("pick one camera board feature, not both (xiao-sense + unverified-map)");
#[cfg(all(feature = "board-xiao-sense", feature = "board-lilygo-tcam-s3-v11"))]
compile_error!("pick one camera board feature, not both (xiao-sense + lilygo-tcam-s3-v11)");
#[cfg(all(feature = "board-lilygo-tcam-s3-v11", feature = "board-unverified-map"))]
compile_error!("pick one camera board feature, not both (lilygo-tcam-s3-v11 + unverified-map)");

// The camera board and the board *profile* (`board.rs`) must agree, or Track 0
// opens the wrong pins at boot. On the Lilygo V1.1 the XIAO's default output
// allow-list `[21, 3, 7, 8]` is SD_CS, camera RESET, camera XCLK and camera D6 --
// the node would drive its own sensor clock as an actuator. `board.rs` selects the
// Lilygo profile from the same feature, and this refuses the combination that
// cannot be made consistent.
#[cfg(all(feature = "board-lilygo-tcam-s3-v11", feature = "board-waveshare-21"))]
compile_error!(
    "`board-lilygo-tcam-s3-v11` and `board-waveshare-21` are different boards; \
     pick one."
);

use anyhow::Context;
// esp32-camera bindings live in their own module (see Cargo.toml `bindings_module`).
use esp_idf_svc::sys::camera as sys;
// ESP_OK / error type come from the base bindings, not the camera module.
use esp_idf_svc::sys::ESP_OK;

/// One board's DVP wiring. `-1` means "not connected on this board".
///
/// A struct rather than loose constants so a board is a single value that can be
/// named, cited and diffed — the previous shape made it impossible to tell, at a
/// glance, whether you were looking at one board's map or a merge of two.
struct CameraPins {
    pwdn: i32,
    reset: i32,
    xclk: i32,
    sccb_sda: i32,
    sccb_scl: i32,
    d0: i32,
    d1: i32,
    d2: i32,
    d3: i32,
    d4: i32,
    d5: i32,
    d6: i32,
    d7: i32,
    vsync: i32,
    href: i32,
    pclk: i32,
}

/// Seeed XIAO ESP32S3 Sense — the OV2640/OV5640 on the Sense expansion board.
///
/// Source: Seeed's own wiki, "Camera Usage in Seeed Studio XIAO ESP32S3 Sense",
/// section *Camera slot circuit design for expansion boards*, which publishes the
/// table of the 14 GPIOs the card slot occupies. Retrieved 2026-09-16 and
/// cross-checked against the `CAMERA_MODEL_XIAO_ESP32S3` entry of the Arduino
/// `camera_pins.h` the same page uses:
///
/// ```text
/// XCLK 10   PCLK 13   VSYNC 38   HREF 47   SIOD(SDA) 40   SIOC(SCL) 39
/// Y2 15  Y3 17  Y4 18  Y5 16  Y6 14  Y7 12  Y8 11  Y9 48
/// ```
///
/// `PWDN` and `RESET` are not broken out on this board, hence `-1`.
///
/// Note D0..D7 map to Y2..Y9 (the sensor's low two bits are not wired), which is
/// why the numbers below look shuffled against the table — that ordering is the
/// convention, not a transcription error.
#[cfg(feature = "board-xiao-sense")]
const PINS: CameraPins = CameraPins {
    pwdn: -1,
    reset: -1,
    xclk: 10,
    sccb_sda: 40,
    sccb_scl: 39,
    d0: 15, // Y2
    d1: 17, // Y3
    d2: 18, // Y4
    d3: 16, // Y5
    d4: 14, // Y6
    d5: 12, // Y7
    d6: 11, // Y8
    d7: 48, // Y9
    vsync: 38,
    href: 47,
    pclk: 13,
};

/// LILYGO T-CameraPlus-S3, hardware revision **V1.0/V1.1 only**.
///
/// Sources, both retrieved 2026-09-16, and they agree exactly:
///
/// * `libraries/private_library/pin_config.h` in `Xinyuan-LilyGO/T-CameraPlus-S3`
///   (branch `arduino-esp32-libs_V2.0.14`, the repo's only branch — there is no
///   `master`), block `#ifdef T_CameraPlus_S3_V1_0_V1_1` plus the shared block
///   below it.
/// * That repo's README, table *"T-CameraPlus-S3_V1.0-V1.1 版本 → camera module
///   ov2640 pins"*.
///
/// ```text
/// XCLK 7   PCLK 10   VSYNC 4   HREF 5   SIOD(SDA) 1   SIOC(SCL) 2
/// RESET 3   PWDN -1 (not wired on this revision)
/// Y2 12  Y3 14  Y4 15  Y5 13  Y6 11  Y7 9  Y8 8  Y9 6
/// ```
///
/// **Do not use this map on a V1.2 board.** Only three camera pins differ, which
/// is exactly why it is dangerous: V1.2 has VSYNC on 3, PWDN on 4 and RESET on
/// -1 — GPIO3 and GPIO4 swap roles. Loading this map on a V1.2 board drives
/// GPIO4 as an input while the board expects it as PWDN. The vendor ships
/// `pin_config.h` with **V1.2 selected**, so the upstream default is the other
/// revision from ours.
///
/// Two board-level facts that do not live in this struct but govern any build
/// using it:
///
/// * **PSRAM is QUAD (QSPI), not octal.** The vendor's `platformio.ini` has
///   `qio_opi` commented out and `qio_qspi` active, their `sdkconfig.defaults`
///   says `CONFIG_SPIRAM_MODE_QUAD=y`, and the README's Arduino table says
///   "QSPI PSRAM". Use `sdkconfig.defaults.camera-lilygo-tcam-v11`, not the
///   XIAO's overlay, which is `MODE_OCT` and measured correct for that board
///   only.
/// * **SCCB is shared.** On V1.0/V1.1 GPIO1/2 also carry the CST816S touch
///   controller (0x15) and the SY6970 PMIC (0x6A). The camera driver takes the
///   bus as its SCCB master. This is why `board.rs` gives this board no sensor
///   I2C bus and no microphone — the firmware's I2S mic is GPIO0/1/2 and would
///   fight the sensor. (V1.2 splits them onto 33/37; another reason not to mix
///   the revisions.)
#[cfg(feature = "board-lilygo-tcam-s3-v11")]
const PINS: CameraPins = CameraPins {
    pwdn: -1,
    reset: 3,
    xclk: 7,
    sccb_sda: 1,
    sccb_scl: 2,
    d0: 12, // Y2
    d1: 14, // Y3
    d2: 15, // Y4
    d3: 13, // Y5
    d4: 11, // Y6
    d5: 9,  // Y7
    d6: 8,  // Y8
    d7: 6,  // Y9
    vsync: 4,
    href: 5,
    pclk: 10,
};

/// The historical map. **Matches no known board** — see the module header for how
/// it came to be here and why it is kept. Quarantined behind its own feature so
/// nothing selects it by accident.
#[cfg(feature = "board-unverified-map")]
const PINS: CameraPins = CameraPins {
    pwdn: -1,
    reset: -1,
    xclk: 15,
    sccb_sda: 4,
    sccb_scl: 5,
    d0: 39,
    d1: 40,
    d2: 41,
    d3: 42,
    d4: 16,
    d5: 17,
    d6: 18,
    d7: 19,
    vsync: 21,
    href: 38,
    pclk: 13,
};

/// Initialise the camera driver (global; call once at boot).
pub fn init() -> anyhow::Result<()> {
    // Zero-initialise the C config, then fill the fields this board needs.
    let mut cfg: sys::camera_config_t = unsafe { core::mem::zeroed() };

    cfg.pin_pwdn = PINS.pwdn;
    cfg.pin_reset = PINS.reset;
    cfg.pin_xclk = PINS.xclk;
    // SCCB (camera-control I2C) pins live in anonymous unions in the binding — the
    // component keeps both the new `pin_sccb_*` and legacy `pin_sscb_*` spellings.
    // Writing a union field is safe in Rust.
    cfg.__bindgen_anon_1.pin_sccb_sda = PINS.sccb_sda;
    cfg.__bindgen_anon_2.pin_sccb_scl = PINS.sccb_scl;
    // 8-bit parallel data bus D0..D7.
    cfg.pin_d0 = PINS.d0;
    cfg.pin_d1 = PINS.d1;
    cfg.pin_d2 = PINS.d2;
    cfg.pin_d3 = PINS.d3;
    cfg.pin_d4 = PINS.d4;
    cfg.pin_d5 = PINS.d5;
    cfg.pin_d6 = PINS.d6;
    cfg.pin_d7 = PINS.d7;
    cfg.pin_vsync = PINS.vsync;
    cfg.pin_href = PINS.href;
    cfg.pin_pclk = PINS.pclk;

    cfg.xclk_freq_hz = 20_000_000;
    cfg.ledc_timer = sys::ledc_timer_t_LEDC_TIMER_0;
    cfg.ledc_channel = sys::ledc_channel_t_LEDC_CHANNEL_0;

    cfg.pixel_format = sys::pixformat_t_PIXFORMAT_JPEG;
    cfg.frame_size = sys::framesize_t_FRAMESIZE_QVGA; // 320×240 — fits one PSRAM fb
    cfg.jpeg_quality = 12; // 0..63, lower = higher quality
    cfg.fb_count = 1;
    cfg.fb_location = sys::camera_fb_location_t_CAMERA_FB_IN_PSRAM;
    cfg.grab_mode = sys::camera_grab_mode_t_CAMERA_GRAB_WHEN_EMPTY;

    let err = unsafe { sys::esp_camera_init(&cfg) };
    if err != ESP_OK {
        anyhow::bail!("esp_camera_init failed (error {err})");
    }
    Ok(())
}

/// Capture one JPEG frame and return it base64-encoded.
pub fn capture_base64() -> anyhow::Result<String> {
    let fb = unsafe { sys::esp_camera_fb_get() };
    if fb.is_null() {
        anyhow::bail!("esp_camera_fb_get returned null (no frame)");
    }
    // Copy the frame out, then always return the buffer to the driver.
    let result = (|| {
        let len = unsafe { (*fb).len } as usize;
        let buf = unsafe { (*fb).buf };
        if buf.is_null() || len == 0 {
            anyhow::bail!("empty frame buffer");
        }
        let data = unsafe { core::slice::from_raw_parts(buf, len) };
        Ok(base64_encode(data))
    })();
    unsafe { sys::esp_camera_fb_return(fb) };
    result.context("camera capture")
}

/// Minimal standard base64 encoder (no external crate in the firmware deps).
fn base64_encode(input: &[u8]) -> String {
    const TABLE: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity((input.len() + 2) / 3 * 4);
    for chunk in input.chunks(3) {
        let b0 = chunk[0] as u32;
        let b1 = *chunk.get(1).unwrap_or(&0) as u32;
        let b2 = *chunk.get(2).unwrap_or(&0) as u32;
        let n = (b0 << 16) | (b1 << 8) | b2;
        out.push(TABLE[((n >> 18) & 0x3F) as usize] as char);
        out.push(TABLE[((n >> 12) & 0x3F) as usize] as char);
        out.push(if chunk.len() > 1 {
            TABLE[((n >> 6) & 0x3F) as usize] as char
        } else {
            '='
        });
        out.push(if chunk.len() > 2 {
            TABLE[(n & 0x3F) as usize] as char
        } else {
            '='
        });
    }
    out
}
